services:
  cobuccio-postgres:
    image: postgres:16.2-alpine3.19
    container_name: cobuccio-postgres
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data
      - TZ=America/Sao_Paulo
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - cobuccio-network

volumes:
  cobuccio-postgres:

networks:
  cobuccio-network:
    driver: bridge
