services:
  cobuccio-postgres:
    image: postgres:17.3-alpine3.21
    container_name: cobuccio-postgres
    # restart: always
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data
      - TZ=America/Sao_Paulo
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - cobuccio-network

  cobuccio-redis:
    image: redis:7.4.2-alpine3.21
    container_name: cobuccio-redis
    # restart: always
    ports:
      - $REDIS_PORT:6379
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - cobuccio-network

volumes:
  cobuccio-postgres:

networks:
  cobuccio-network:
    driver: bridge
